export const AppIcon = {
  //Common
  irtech: require('./icons/irtech.png'),
  setting_copy_right: require('../assets/icons/copy_right.png'),
  chevron_left: require('../assets/icons/left.png'),
  chevron_up: require('../assets/icons/up.png'),
  chevron_right: require('../assets/icons/right.png'),
  chevron_down: require('../assets/icons/down.png'),
  calendar: require('../assets/icons/input_calendar.png'),
  x: require('../assets/icons/x.png'),
  check_round: require('../assets/icons/check_round.png'),
  info_round: require('../assets/icons/info_round.png'),
  camera: require('../assets/icons/camera.png'),
  search: require('../assets/icons/search.png'),
  filter: require('../assets/icons/filter.png'),
  trash: require('../assets/icons/trash.png'),
  edit: require('../assets/icons/edit.png'),
  file: require('../assets/icons/file.png'),
  image: require('../assets/icons/image.png'),
  upload: require('../assets/icons/upload.png'),
  tick: require('../assets/icons/tick.png'),
  tick_cirle: require('../assets/icons/tick_circle.png'),
  info: require('../assets/icons/info.png'),
  bell_solid: require('../assets/icons/bell_solid.png'),
  clean: require('../assets/icons/clean.png'),
  download: require('../assets/icons/download.png'),
  download_cirle: require('../assets/icons/circle_down.png'),
  plus: require('../assets/icons/plus.png'),
  minus: require('../assets/icons/minus.png'),
  contract_emty: require('../assets/icons/contract_emty.png'),
  tick_double: require('../assets/icons/tick_double.png'),
  //Input
  clear_text: require('../assets/icons/clear_text.png'),
  visible: require('../assets/icons/visible.png'),
  invisible: require('../assets/icons/invisible.png'),
  //Toast
  toast_warning: require('./icons/toast_warning.png'),
  toast_success: require('./icons/toast_success.png'),
  //Tabbar
  home_light: require('../assets/icons/home.png'),
  home_bold: require('../assets/icons/home_bold.png'),
  product_light: require('../assets/icons/product.png'),
  product_bold: require('../assets/icons/product_bold.png'),
  contract_light: require('../assets/icons/contract.png'),
  contract_bold: require('../assets/icons/contract_bold.png'),
  report_light: require('../assets/icons/report.png'),
  report_bold: require('../assets/icons/report_bold.png'),
  profile_light: require('../assets/icons/profile_light.png'),
  profile_bold: require('../assets/icons/profile_bold.png'),
  kcs_light: require('../assets/icons/kcs_light.png'),
  kcs_bold: require('../assets/icons/kcs_bold.png'),
  logout: require('../assets/icons/log_out.png'),
  lock: require('../assets/icons/lock.png'),
  profile: require('../assets/icons/profile.png'),
  wiIcon: require('../assets/icons/Nhapkho.png'),
  weIcon: require('../assets/icons/Xuatkho.png'),
  wetIcon: require('../assets/icons/Xuatdieuchuyen.png'),
  witIcon: require('../assets/icons/Nhapdieuchuyen.png'),
  filterIcon: require('../assets/icons/Filter_Erp.png'),
  checkBoxOutLine: require('../assets/icons/Checkbox_outline.png'),
  checkBoxTick: require('../assets/icons/Checkbox.png'),
  //FILE
  doc: require('../assets/icons/doc.png'),
  edi: require('../assets/icons/edi.png'),
  excel: require('../assets/icons/excel.png'),
  pdf: require('../assets/icons/pdf.png'),
  pttx: require('../assets/icons/pttx.png'),
  txt: require('../assets/icons/txt.png'),
  danger: require('../assets/icons/danger.png'),
  unit: require('../assets/icons/unit.png'),
  resize: require('../assets/icons/Resize.png'),
  chat: require('../assets/icons/Chat.png'),
  Xlsx: require('../assets/icons/Xlsx.png'),
  delete: require('../assets/icons/Delete.png'),
};

export const AppImage = {
  header_img_login: require('../assets/images/header_login.png'),
  footer_img_login: require('../assets/images/footer_login.png'),
  // Default Image
  default: require('./images/default.jpeg'),
  empty_search: require('../assets/images/empty_search.png'),
  //app
  // app_logo: require('./images/logo.png'),
  splash: require('./images/splash.png'),
  avatar: require('./images/avatar.png'),
  logo_splash: require('./images/logo_splash.png'),
  logo_white: require('./images/logo_white.png'),
  header_profile: require('./images/header_profile_bg_img.png'),
  login_bg: require('./images/login_bg.png'),
  selected_detail_bg: require('./images/selected_detail_bg.png'),
  detail_bg: require('./images/detail_bg.png'),
};